travis:
  secure:
    BINSTAR_TOKEN: g8J4aNswKfETu2yPCQw5g651YcmM3E/pxVx2mBgY28QOZR6BuIdh2qrdbJT+29W9/XJj2eMurMwCtdqZxV5FBXqEmQLfH1lmh9Ij+I40AuyOEVPEBc7X7z6BGkIGGE/M9GGSKrJkUIv0W9tw4JhGtPf+vFKSC3IhYfjTmTrvppNaiWM+GyNH55ix5oqUlnzAfSKptQaFuFNioK2ZVuM4NWQDpnPCtjIGWv4c0KrhhY+Y+UY5j5WOfXGF5YgDcIs6KoOMnb2fIsVciVIVT7aSGQDCUNB/PuYztF8xC/NQo2AXpuP+TT8p1NNwHjJkYXgwUwOI/kBhe8wuyFgoHSQ4ErnFbg9pWcG2Nj5ghL7xN/W94ye5P/FM0UwBC0Lufda5eC5zLefEYYOQ0KH5OR+tluwt4+6vD8qDVqu6HJG7oHgNcncqFB0EPi9NI9+AaTzpsoz3R5ldIwA1GLpp0D7PffobgYihv+7m1nYOUdnIXrHSrASOjVg2Rb5P/mD5/aQO78SEfRuR4PXd/hkceHFrPoxPw/Q1tOEZNCw3zz6XO1KF8egDqlaVE3tbbMNNuaE4vHGQfeWVAs8sg3/UvNfszcpwiOAgiASQiXZLTQ1spva4sd0bY/PO5Xbm2b4s7UMHwHcx1ERIpwhOIKF8QfdfaR18ErTaQ3UvBxRSTlLzvd8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
